version: "3.9"

services:
  db:
    image: postgres:15
    container_name: finstatik_db
    restart: always
    environment:
      POSTGRES_USER: finuser
      POSTGRES_PASSWORD: finpass
      POSTGRES_DB: finstatik
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build: .
    container_name: finstatik_backend
    restart: always
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  db_data:
